version: "3.8"

services:
  youtube-analysis-service:
    build: .
    container_name: youtube-analysis-service
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - GPTZERO_API_KEY=${GPTZERO_API_KEY}
      - UPLOAD_DIR=./uploads
      - SCREENSHOT_DIR=./screenshots
      - AUDIO_DIR=./audio
      - DB_PATH=./data/analysis.db
      - LOG_LEVEL=info
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./screenshots:/app/screenshots
      - ./audio:/app/audio
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:8080/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "1.0"
        reservations:
          memory: 1G
          cpus: "0.5"

networks:
  default:
    driver: bridge
